<?php
echo "<!DOCTYPE html>";
echo "<html lang=\"en\">";
echo "<head>";
echo "<meta charset=\"UTF-8\" />";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />";
echo "<title>Keyur Coffee House</title>";
echo "<link rel=\"stylesheet\" href=\"style.css\" />";
echo "</head>";
echo "<body>";
echo "";
echo "<!-- Navbar -->";
echo "<header>";
echo "<div class=\"logo\">☕ Keyur Coffee</div>";
echo "<nav>";
echo "<a href=\"#home\">Home</a>";
echo "<a href=\"#menu\">Menu</a>";
echo "<a href=\"#about\">About</a>";
echo "<a href=\"#contact\">Contact</a>";
echo "</nav>";
echo "</header>";
echo "";
echo "<!-- Hero Section -->";
echo "<section class=\"hero\" id=\"home\">";
echo "<div class=\"hero-text\">";
echo "<h1>Fresh Coffee, Fresh Mood ☕</h1>";
echo "<p>Enjoy premium roasted coffee beans and delicious snacks.</p>";
echo "<button>Order Now</button>";
echo "</div>";
echo "</section>";
echo "";
echo "<!-- Menu Section -->";
echo "<section class=\"menu\" id=\"menu\">";
echo "<h2>Our Coffee Menu</h2>";
echo "<div class=\"menu-items\">";
echo "";
echo "<div class=\"card\">";
echo "<img src=\"images/espresso.jpg\" alt=\"Espresso\">";
echo "<h3>Espresso</h3>";
echo "<p>Strong & bold coffee shot.</p>";
echo "<span>₹120</span>";
echo "</div>";
echo "";
echo "<div class=\"card\">";
echo "<img src=\"images/cappuccino.jpg\" alt=\"Cappuccino\">";
echo "<h3>Cappuccino</h3>";
echo "<p>Milk foam with rich taste.</p>";
echo "<span>₹180</span>";
echo "</div>";
echo "";
echo "<div class=\"card\">";
echo "<img src=\"images/latte.jpg\" alt=\"Latte\">";
echo "<h3>Latte</h3>";
echo "<p>Smooth creamy coffee.</p>";
echo "<span>₹200</span>";
echo "</div>";
echo "";
echo "</div>";
echo "</section>";
echo "";
echo "<!-- About Section -->";
echo "<section class=\"about\" id=\"about\">";
echo "<h2>About Us</h2>";
echo "<p>";
echo "Welcome to <b>Keyur Coffee House</b>!";
echo "We serve freshly brewed coffee with love and warmth.";
echo "Our beans are handpicked and roasted to perfection.";
echo "</p>";
echo "</section>";
echo "";
echo "<!-- Contact Section -->";
echo "<section class=\"contact\" id=\"contact\">";
echo "<h2>Contact Us</h2>";
echo "";
echo "<div class=\"contact-box\">";
echo "<p><b>📍 Location:</b> Pune, India</p>";
echo "<p><b>📞 Phone:</b> +91 98765 43210</p>";
echo "<p><b>✉ Email:</b> keyurcoffee@gmail.com</p>";
echo "</div>";
echo "";
echo "<form>";
echo "<input type=\"text\" placeholder=\"Your Name\" required />";
echo "<input type=\"email\" placeholder=\"Your Email\" required />";
echo "<textarea placeholder=\"Your Message\" required></textarea>";
echo "<button type=\"submit\">Send Message</button>";
echo "</form>";
echo "</section>";
echo "";
echo "<!-- Footer -->";
echo "<footer>";
echo "<p>© 2026 Keyur Coffee House | All Rights Reserved</p>";
echo "</footer>";
echo "";
echo "</body>";
echo "</html>";
echo "";
?>